version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: percentage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    container_name: percentage-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend: